//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Demo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesBillDetails
    {
        public int id { get; set; }
        public Nullable<int> prod_id { get; set; }
        public Nullable<int> salesBillId { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
    
        public virtual salesBill salesBill { get; set; }
        public virtual Products Products { get; set; }
    }
}
